# -*- coding: utf-8 -*-
"""UL-Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16H5S3IrgEuLlmbz5IH3WSosSMruB0RhK
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score, davies_bouldin_score
from sklearn.ensemble import IsolationForest
from sklearn.decomposition import PCA

#load sample data
df = pd.read_csv('creditcard.csv')
X = df.drop(columns=['Class','Time'], errors='ignore')
X_sample = X.sample(n=10000, random_state=42)

#scale features
X_scaled = StandardScaler().fit_transform(X_sample)

#kmeans elbow method
inertia = []
for k in range(2, 11):
    km = KMeans(n_clusters=k, random_state=42)
    inertia.append(km.fit(X_scaled).inertia_)

# elbow curve
plt.figure(figsize=(8, 5))
plt.plot(range(2, 11), inertia, marker='o')
plt.title('Elbow Method For Optimal k')
plt.xlabel('Number of Clusters')
plt.ylabel('Inertia')
plt.show()

#clustering scores
km = KMeans(n_clusters=3, random_state=42, n_init=10)
labels = km.fit_predict(X_scaled)

print("Sil :", silhouette_score(X_scaled,labels))
print("DB :", davies_bouldin_score(X_scaled,labels))

import matplotlib.pyplot as plt
from sklearn.cluster import AgglomerativeClustering, DBSCAN
from scipy.cluster.hierarchy import dendrogram, linkage

#hierarchical dendrogram
linked = linkage(X_scaled, method='ward')

# plot dendrogram
plt.figure(figsize=(10, 5))
dendrogram(linked, truncate_mode='level', p=5)
plt.title('Hierarchical Clustering Dendrogram')
plt.xlabel('Cluster Nodes')
plt.ylabel('Euclidean Distance')
plt.show()

#fit hierarchical clustering model
hc =AgglomerativeClustering(n_clusters=3)
hc_labels = hc.fit_predict(X_scaled)

#dbscan clustering
db = DBSCAN(eps=0.5, min_samples=5)
db_labels =db.fit_predict(X_scaled)

# Reduce dimensions to 2D
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)

# K-Means visualization
plt.figure(figsize=(8,6))
plt.scatter(
    X_pca[:,0],
    X_pca[:,1],
    c=labels,
    cmap='viridis',
    s=10
)
plt.title("K-Means Clusters (PCA 2D)")
plt.xlabel("Principal Component 1")
plt.ylabel("Principal Component 2")
plt.colorbar(label="Cluster")
plt.show()

# Hierarchical Clustering visualization
plt.figure(figsize=(8,6))
plt.scatter(
    X_pca[:,0],
    X_pca[:,1],
    c=hc_labels,
    cmap='rainbow',
    s=10
)
plt.title("Hierarchical Clustering (PCA 2D)")
plt.xlabel("Principal Component 1")
plt.ylabel("Principal Component 2")
plt.colorbar(label="Cluster")
plt.show()

# DBSCAN visualization
plt.figure(figsize=(8,6))
plt.scatter(
    X_pca[:,0],
    X_pca[:,1],
    c=db_labels,
    cmap='tab10',
    s=10
)
plt.title("DBSCAN Clusters (PCA 2D)")
plt.xlabel("Principal Component 1")
plt.ylabel("Principal Component 2")
plt.colorbar(label="Cluster / Noise")
plt.show()

from sklearn.ensemble import IsolationForest

iso_forest = IsolationForest(
    contamination=0.01,
    random_state=42
)

iso_preds = iso_forest.fit_predict(X_scaled)

plt.figure(figsize=(8,6))

plt.scatter(
    X_pca[iso_preds == 1, 0],
    X_pca[iso_preds == 1, 1],
    c='blue',
    s=10,
    label='Normal'
)

plt.scatter(
    X_pca[iso_preds == -1, 0],
    X_pca[iso_preds == -1, 1],
    c='red',
    s=30,
    label='Anomaly'
)

plt.title("Isolation Forest Anomaly Detection")
plt.xlabel("Principal Component 1")
plt.ylabel("Principal Component 2")
plt.legend()
plt.show()

print("Normal Transactions :", (iso_preds == 1).sum())
print("Anomalies Detected  :", (iso_preds == -1).sum())

print("\nMethod\t\t\tSilhouette\tDB Score")
print(f"K-Means\t\t\t{silhouette_score(X_scaled, labels):.4f}\t\t{davies_bouldin_score(X_scaled, labels):.4f}")

print(f"Hierarchical\t\t{silhouette_score(X_scaled, hc_labels):.4f}\t\t{davies_bouldin_score(X_scaled, hc_labels):.4f}")

mask = db_labels != -1
if len(set(db_labels[mask])) > 1:
    print(f"DBSCAN\t\t\t{silhouette_score(X_scaled[mask], db_labels[mask]):.4f}\t\t{davies_bouldin_score(X_scaled[mask], db_labels[mask]):.4f}")

print("\nIsolation Forest")
print("Detected Anomalies :", (iso_preds == -1).sum())
print("Detected Normal Points :", (iso_preds == 1).sum())